/* ============================================================
   Popote — données : ingrédients (prix CH/FR) & recettes
   Quantités : par personne. Unités : g (prix/kg), ml (prix/L), pc (prix/pièce)
   ============================================================ */

const RAYONS = {
  FL: { n: 'Fruits & Légumes', e: '🥕' },
  VP: { n: 'Viande & Poisson', e: '🥩' },
  CR: { n: 'Crèmerie & Frais', e: '🧀' },
  EP: { n: 'Épicerie', e: '🥫' },
  SU: { n: 'Surgelés', e: '🧊' },
  BO: { n: 'Boulangerie', e: '🥖' },
  PL: { n: 'Fond de placard', e: '🧂' },
};

/* id : [nom, rayon, unité, prix EUR, prix CHF] — prix par kg, par L ou par pièce */
const INGREDIENTS = {
  /* — Fruits & Légumes — */
  oignon:        ['Oignons', 'FL', 'g', 1.8, 2.8],
  oignonRouge:   ['Oignon rouge', 'FL', 'g', 2.2, 3.2],
  ail:           ['Ail', 'FL', 'g', 8, 12],
  echalote:      ['Échalotes', 'FL', 'g', 4, 6],
  carotte:       ['Carottes', 'FL', 'g', 1.3, 2.2],
  pommeDeTerre:  ['Pommes de terre', 'FL', 'g', 1.5, 2.2],
  patateDouce:   ['Patate douce', 'FL', 'g', 2.8, 4.5],
  courgette:     ['Courgettes', 'FL', 'g', 2.5, 3.8],
  aubergine:     ['Aubergine', 'FL', 'g', 2.8, 4.5],
  poivron:       ['Poivrons', 'FL', 'g', 3.5, 5.5],
  tomate:        ['Tomates', 'FL', 'g', 2.8, 4.2],
  tomateCerise:  ['Tomates cerises', 'FL', 'g', 5, 8],
  brocoli:       ['Brocoli', 'FL', 'g', 3, 4.5],
  chouFleur:     ['Chou-fleur', 'FL', 'g', 2.8, 4],
  epinardsFrais: ['Épinards frais', 'FL', 'g', 6, 9],
  champignon:    ['Champignons de Paris', 'FL', 'g', 6, 9],
  poireau:       ['Poireaux', 'FL', 'g', 2.5, 3.8],
  potiron:       ['Courge / potiron', 'FL', 'g', 2.5, 3.5],
  concombre:     ['Concombre', 'FL', 'pc', 1, 1.6],
  salade:        ['Salade verte', 'FL', 'pc', 1.2, 2],
  avocat:        ['Avocat', 'FL', 'pc', 1.2, 1.8],
  citron:        ['Citron', 'FL', 'pc', 0.6, 0.9],
  citronVert:    ['Citron vert', 'FL', 'pc', 0.7, 1],
  gingembre:     ['Gingembre frais', 'FL', 'g', 8, 12],
  persil:        ['Persil (bouquet)', 'FL', 'pc', 1, 1.6],
  coriandre:     ['Coriandre (bouquet)', 'FL', 'pc', 1, 1.6],
  basilic:       ['Basilic (bouquet)', 'FL', 'pc', 1.5, 2.5],

  /* — Viande & Poisson — */
  pouletFilet:   ['Filet de poulet', 'VP', 'g', 11, 24],
  pouletCuisse:  ['Cuisses de poulet', 'VP', 'g', 6, 12],
  pouletEntier:  ['Poulet entier (~1,4 kg)', 'VP', 'pc', 8, 14],
  boeufHache:    ['Bœuf haché', 'VP', 'g', 11, 18],
  boeufMijote:   ['Bœuf à mijoter', 'VP', 'g', 13, 26],
  lardons:       ['Lardons fumés', 'VP', 'g', 10, 18],
  filetMignon:   ['Filet mignon de porc', 'VP', 'g', 12, 20],
  saucisseFumee: ['Saucisse fumée', 'VP', 'g', 10, 16],
  saumon:        ['Filet de saumon', 'VP', 'g', 20, 35],
  cabillaud:     ['Dos de cabillaud', 'VP', 'g', 18, 30],
  crevettes:     ['Crevettes décortiquées', 'VP', 'g', 16, 28],

  /* — Crèmerie & Frais — */
  oeuf:          ['Œufs', 'CR', 'pc', 0.35, 0.55],
  lait:          ['Lait', 'CR', 'ml', 1.1, 1.6],
  creme:         ['Crème entière', 'CR', 'ml', 4.5, 7],
  beurre:        ['Beurre', 'CR', 'g', 8, 13],
  yaourtNature:  ['Yaourt nature', 'CR', 'pc', 0.5, 0.8],
  fromageRape:   ['Fromage râpé', 'CR', 'g', 12, 20],
  parmesan:      ['Parmesan', 'CR', 'g', 18, 30],
  feta:          ['Feta', 'CR', 'g', 12, 18],
  mozzarella:    ['Mozzarella (boule 125 g)', 'CR', 'pc', 0.9, 1.4],
  chevre:        ['Fromage de chèvre', 'CR', 'g', 15, 22],
  gruyere:       ['Gruyère', 'CR', 'g', 15, 20],
  fromTartiflette: ['Reblochon / fromage à tartiflette', 'CR', 'pc', 5.5, 8.5],
  ricotta:       ['Ricotta (pot 250 g)', 'CR', 'pc', 1.8, 2.8],
  tofu:          ['Tofu nature', 'CR', 'g', 8, 12],
  tofuFume:      ['Tofu fumé', 'CR', 'g', 10, 15],
  pateFeuilletee:['Pâte feuilletée', 'CR', 'pc', 1.5, 2.4],
  pateAPizza:    ['Pâte à pizza', 'CR', 'pc', 1.5, 2.4],

  /* — Épicerie — */
  pates:         ['Pâtes (spaghetti, penne…)', 'EP', 'g', 1.8, 2.6],
  riz:           ['Riz', 'EP', 'g', 2.2, 3.2],
  rizBasmati:    ['Riz basmati', 'EP', 'g', 3, 4.2],
  quinoa:        ['Quinoa', 'EP', 'g', 6, 9],
  semoule:       ['Semoule de couscous', 'EP', 'g', 2.5, 3.5],
  boulgour:      ['Boulgour', 'EP', 'g', 3, 4.2],
  polenta:       ['Polenta', 'EP', 'g', 2, 3],
  gnocchi:       ['Gnocchis', 'EP', 'g', 3, 4.5],
  plaquesLasagnes: ['Plaques à lasagnes', 'EP', 'g', 3, 4.5],
  nouillesAsiat: ['Nouilles asiatiques', 'EP', 'g', 4, 6],
  lentillesVertes: ['Lentilles vertes', 'EP', 'g', 3.5, 5],
  lentillesCorail: ['Lentilles corail', 'EP', 'g', 4, 5.5],
  poisChiches:   ['Pois chiches (boîte 400 g)', 'EP', 'pc', 0.9, 1.4],
  haricotsRouges:['Haricots rouges (boîte 400 g)', 'EP', 'pc', 0.9, 1.4],
  mais:          ['Maïs (boîte)', 'EP', 'pc', 1, 1.5],
  tomatesConcassees: ['Tomates concassées (boîte 400 g)', 'EP', 'pc', 0.9, 1.3],
  concentreTomate: ['Concentré de tomate', 'EP', 'pc', 0.8, 1.2],
  laitCoco:      ['Lait de coco (400 ml)', 'EP', 'pc', 1.5, 2.2],
  thon:          ['Thon (boîte 140 g)', 'EP', 'pc', 1.8, 2.6],
  olives:        ['Olives noires (bocal)', 'EP', 'pc', 1.5, 2.2],
  beurreCacahuete: ['Beurre de cacahuète', 'EP', 'pc', 3, 4.5],
  cajou:         ['Noix de cajou', 'EP', 'g', 14, 20],
  amandes:       ['Amandes effilées', 'EP', 'g', 15, 22],
  tortillas:     ['Tortillas de blé', 'EP', 'pc', 0.3, 0.45],
  painBurger:    ['Pains à burger', 'EP', 'pc', 0.45, 0.65],
  vinCuisine:    ['Vin rouge de cuisine (75 cl)', 'EP', 'pc', 3, 4.5],

  /* — Surgelés — */
  petitsPois:    ['Petits pois surgelés', 'SU', 'g', 2.5, 3.8],
  epinardsSurg:  ['Épinards surgelés', 'SU', 'g', 2.5, 4],
  haricotsVerts: ['Haricots verts surgelés', 'SU', 'g', 3, 4.5],

  /* — Boulangerie — */
  pain:          ['Pain de campagne', 'BO', 'pc', 1.4, 2.2],

  /* — Fond de placard (souvent déjà à la maison) — */
  huileOlive:    ["Huile d'olive", 'PL', 'ml', 8, 12],
  sauceSoja:     ['Sauce soja', 'PL', 'ml', 6, 9],
  vinaigre:      ['Vinaigre', 'PL', 'ml', 2, 3],
  moutarde:      ['Moutarde', 'PL', 'pc', 1.5, 2.2],
  miel:          ['Miel', 'PL', 'pc', 4, 6],
  farine:        ['Farine', 'PL', 'g', 1.2, 1.8],
  bouillon:      ['Cube de bouillon', 'PL', 'pc', 0.15, 0.25],
  curryPoudre:   ['Curry en poudre', 'PL', 'pc', 1.5, 2.2],
  paprika:       ['Paprika', 'PL', 'pc', 1.5, 2.2],
  cumin:         ['Cumin', 'PL', 'pc', 1.5, 2.2],
  herbesProvence:['Herbes de Provence', 'PL', 'pc', 1.5, 2.2],
  sesame:        ['Graines de sésame', 'PL', 'pc', 2, 3],
};

/* ============================================================
   Recettes.
   cat : vegan | vege | viande | poisson
   base : pates | riz | pdt | legumineuse | pain | cereale | autre
   Allergènes / régime : g gluten, l lactose, nu fruits à coque, pk porc
   t : temps actif (min) · c : cuisson passive (min) · oven : passe au four
   season : mois où la recette brille ([] = toute l'année)
   steps : [phase, texte] — 1 préparation · 2 cuisson · 3 finition
   ============================================================ */

const RECIPES = [
  /* ——— VEGAN / VÉGÉTARIEN ——— */
  {
    id: 'chiliSinCarne', n: 'Chili sin carne & riz', e: '🌶️', cat: 'vegan', base: 'riz',
    tags: ['batch', 'budget', 'épicé'], g: 0, l: 0, nu: 0, pk: 0, t: 20, c: 25, oven: 0, kcal: 520, season: [],
    ing: [['oignon', 60], ['ail', 5], ['poivron', 80], ['haricotsRouges', 0.5], ['mais', 0.3], ['tomatesConcassees', 0.5], ['riz', 75], ['cumin', 0.05], ['paprika', 0.05], ['huileOlive', 10]],
    steps: [
      [1, "Émincer l'oignon et l'ail, couper le poivron en dés."],
      [2, "Faire revenir oignon, ail et poivron 5 min dans l'huile."],
      [2, 'Ajouter tomates, haricots égouttés, maïs, cumin et paprika. Mijoter 20 min.'],
      [2, 'Cuire le riz 12 min dans un grand volume d’eau salée.'],
      [3, 'Rectifier l’assaisonnement, servir le chili sur le riz.'],
    ],
    tip: 'Encore meilleur réchauffé — 4 jours au frigo, 3 mois au congélateur.',
  },
  {
    id: 'dahlCorail', n: 'Dahl de lentilles corail coco', e: '🍛', cat: 'vegan', base: 'legumineuse',
    tags: ['batch', 'budget', 'rapide', 'réconfort'], g: 0, l: 0, nu: 0, pk: 0, t: 15, c: 20, oven: 0, kcal: 540, season: [],
    ing: [['lentillesCorail', 80], ['laitCoco', 0.5], ['tomatesConcassees', 0.5], ['oignon', 60], ['ail', 5], ['gingembre', 8], ['curryPoudre', 0.1], ['riz', 60], ['coriandre', 0.2], ['huileOlive', 10]],
    steps: [
      [1, "Émincer l'oignon, hacher ail et gingembre."],
      [2, 'Faire revenir oignon, ail, gingembre et curry 3 min.'],
      [2, 'Ajouter lentilles, tomates, lait de coco et 1 verre d’eau. Mijoter 18 min.'],
      [2, 'Cuire le riz en parallèle.'],
      [3, 'Parsemer de coriandre fraîche avant de servir.'],
    ],
    tip: 'Épaissit au frigo : ajouter un trait d’eau au réchauffage. Se congèle parfaitement.',
  },
  {
    id: 'soupePotiron', n: 'Velouté de courge rôtie', e: '🎃', cat: 'vegan', base: 'autre',
    tags: ['batch', 'léger', 'réconfort'], g: 1, l: 0, nu: 0, pk: 0, t: 15, c: 35, oven: 1, kcal: 320, season: [10, 11, 12, 1, 2, 3],
    ing: [['potiron', 300], ['carotte', 80], ['oignon', 60], ['bouillon', 0.5], ['creme', 20], ['pain', 0.3], ['huileOlive', 10]],
    steps: [
      [1, 'Couper courge, carottes et oignon en gros cubes.'],
      [2, 'Rôtir les légumes 30 min au four à 200 °C avec un filet d’huile.'],
      [2, 'Mixer avec le bouillon dilué dans 500 ml d’eau chaude.'],
      [3, 'Ajouter la crème, servir avec le pain grillé.'],
    ],
    tip: 'Le rôtissage concentre les saveurs. 4 jours au frigo, se congèle sans la crème.',
  },
  {
    id: 'ratatouille', n: 'Ratatouille & semoule', e: '🍆', cat: 'vegan', base: 'cereale',
    tags: ['batch', 'léger', 'provençal'], g: 1, l: 0, nu: 0, pk: 0, t: 20, c: 35, oven: 0, kcal: 430, season: [6, 7, 8, 9, 10],
    ing: [['aubergine', 100], ['courgette', 100], ['poivron', 80], ['tomate', 150], ['oignon', 60], ['ail', 5], ['herbesProvence', 0.1], ['semoule', 70], ['huileOlive', 15]],
    steps: [
      [1, 'Couper tous les légumes en dés réguliers.'],
      [2, "Faire revenir l'oignon et l'ail, puis ajouter les légumes et les herbes."],
      [2, 'Mijoter à couvert 35 min en remuant de temps en temps.'],
      [3, 'Verser de l’eau bouillante sur la semoule (même volume), couvrir 5 min, égrainer.'],
    ],
    tip: 'Encore meilleure le lendemain. Excellente froide en salade avec un filet de citron.',
  },
  {
    id: 'gratinGnocchis', n: 'Gnocchis gratinés tomate-mozza', e: '🧀', cat: 'vege', base: 'pdt',
    tags: ['rapide', 'réconfort', 'famille'], g: 1, l: 1, nu: 0, pk: 0, t: 15, c: 20, oven: 1, kcal: 620, season: [],
    ing: [['gnocchi', 180], ['tomatesConcassees', 0.5], ['mozzarella', 0.5], ['oignon', 40], ['ail', 5], ['basilic', 0.2], ['huileOlive', 10]],
    steps: [
      [1, "Émincer l'oignon et l'ail. Préchauffer le four à 210 °C."],
      [2, 'Faire une sauce : oignon, ail, tomates, 10 min à feu moyen.'],
      [2, 'Mélanger les gnocchis crus à la sauce dans un plat, couvrir de mozzarella.'],
      [2, 'Enfourner 20 min jusqu’à ce que le fromage gratine.'],
      [3, 'Parsemer de basilic frais.'],
    ],
    tip: 'Les gnocchis cuisent directement dans la sauce — zéro casserole en plus.',
  },
  {
    id: 'risottoChampi', n: 'Risotto aux champignons', e: '🍄', cat: 'vege', base: 'riz',
    tags: ['réconfort', 'gourmand'], g: 0, l: 1, nu: 0, pk: 0, t: 30, c: 0, oven: 0, kcal: 580, season: [9, 10, 11, 12, 1, 2],
    ing: [['riz', 80], ['champignon', 120], ['oignon', 50], ['parmesan', 25], ['beurre', 15], ['bouillon', 0.5], ['huileOlive', 10]],
    steps: [
      [1, "Émincer champignons et oignon. Préparer 500 ml de bouillon chaud."],
      [2, 'Dorer les champignons à feu vif, réserver.'],
      [2, "Nacrer le riz avec l'oignon 2 min, puis ajouter le bouillon louche par louche pendant 18 min."],
      [3, 'Hors du feu, incorporer beurre, parmesan et champignons. Couvrir 2 min.'],
    ],
    tip: 'Le risotto se réchauffe très bien avec un trait de bouillon ou de lait.',
  },
  {
    id: 'buddhaBowl', n: 'Buddha bowl quinoa & pois chiches rôtis', e: '🥗', cat: 'vegan', base: 'cereale',
    tags: ['léger', 'frais', 'équilibré'], g: 0, l: 0, nu: 0, pk: 0, t: 20, c: 20, oven: 1, kcal: 560, season: [4, 5, 6, 7, 8, 9],
    ing: [['quinoa', 70], ['poisChiches', 0.5], ['avocat', 0.5], ['carotte', 60], ['concombre', 0.3], ['citron', 0.5], ['paprika', 0.05], ['sesame', 0.1], ['huileOlive', 15]],
    steps: [
      [1, 'Rincer le quinoa. Égoutter les pois chiches et les sécher.'],
      [2, 'Rôtir les pois chiches 20 min à 200 °C avec huile et paprika.'],
      [2, "Cuire le quinoa 12 min dans 2 fois son volume d'eau."],
      [1, 'Râper la carotte, couper concombre et avocat.'],
      [3, 'Dresser en bol, arroser de jus de citron, huile d’olive et sésame.'],
    ],
    tip: 'Prépare les composants à l’avance et assemble au dernier moment — l’avocat en dernier.',
  },
  {
    id: 'patesCourgetteChevre', n: 'Pâtes crémeuses courgette-chèvre', e: '🍝', cat: 'vege', base: 'pates',
    tags: ['rapide', 'budget'], g: 1, l: 1, nu: 0, pk: 0, t: 20, c: 0, oven: 0, kcal: 610, season: [5, 6, 7, 8, 9],
    ing: [['pates', 100], ['courgette', 150], ['chevre', 40], ['creme', 30], ['ail', 5], ['huileOlive', 10]],
    steps: [
      [1, "Couper la courgette en demi-lunes, hacher l'ail."],
      [2, 'Cuire les pâtes al dente. Réserver une louche d’eau de cuisson.'],
      [2, "Faire dorer courgettes et ail 8 min, ajouter crème et chèvre pour une sauce onctueuse."],
      [3, "Mélanger pâtes et sauce, détendre avec l'eau de cuisson."],
    ],
    tip: 'L’eau de cuisson des pâtes lie la sauce mieux que n’importe quelle crème en plus.',
  },
  {
    id: 'lasagnesVege', n: 'Lasagnes épinards-ricotta', e: '🥬', cat: 'vege', base: 'pates',
    tags: ['batch', 'famille', 'réconfort'], g: 1, l: 1, nu: 0, pk: 0, t: 30, c: 40, oven: 1, kcal: 650, season: [],
    ing: [['plaquesLasagnes', 80], ['epinardsSurg', 150], ['ricotta', 0.5], ['tomatesConcassees', 0.5], ['oignon', 50], ['fromageRape', 30], ['lait', 50], ['farine', 10], ['beurre', 10]],
    steps: [
      [1, 'Décongeler et presser les épinards. Préchauffer le four à 190 °C.'],
      [2, "Faire une sauce tomate rapide avec l'oignon (10 min), et une béchamel légère (beurre, farine, lait)."],
      [1, 'Mélanger épinards et ricotta, saler, poivrer, muscade si tu en as.'],
      [2, 'Monter les couches : tomate, plaques, épinards-ricotta, béchamel. Finir par le râpé.'],
      [2, 'Enfourner 40 min à 190 °C.'],
    ],
    tip: 'Se découpe en portions à congeler individuellement — le plat batch par excellence.',
  },
  {
    id: 'tajineLegumes', n: 'Tajine de légumes & pois chiches', e: '🥘', cat: 'vegan', base: 'cereale',
    tags: ['batch', 'parfumé', 'léger'], g: 1, l: 0, nu: 0, pk: 0, t: 20, c: 30, oven: 0, kcal: 480, season: [],
    ing: [['carotte', 100], ['courgette', 100], ['patateDouce', 100], ['poisChiches', 0.5], ['oignon', 60], ['tomatesConcassees', 0.5], ['cumin', 0.1], ['semoule', 70], ['coriandre', 0.2], ['huileOlive', 10]],
    steps: [
      [1, 'Couper les légumes en morceaux généreux.'],
      [2, "Faire revenir l'oignon et le cumin, ajouter légumes, tomates, pois chiches et 1 verre d'eau."],
      [2, 'Mijoter à couvert 30 min.'],
      [3, 'Préparer la semoule, servir le tajine dessus avec la coriandre.'],
    ],
    tip: 'Une poignée de raisins secs ou d’amandes le rend encore plus festif.',
  },
  {
    id: 'curryThaiTofu', n: 'Curry thaï de légumes au tofu', e: '🥥', cat: 'vegan', base: 'riz',
    tags: ['parfumé', 'rapide'], g: 0, l: 0, nu: 0, pk: 0, t: 25, c: 0, oven: 0, kcal: 560, season: [],
    ing: [['tofu', 100], ['laitCoco', 0.5], ['brocoli', 100], ['poivron', 60], ['gingembre', 8], ['ail', 5], ['curryPoudre', 0.1], ['sauceSoja', 10], ['rizBasmati', 70], ['citronVert', 0.5], ['huileOlive', 10]],
    steps: [
      [1, 'Couper le tofu en cubes, le brocoli en fleurettes, le poivron en lanières.'],
      [2, 'Dorer le tofu à feu vif, réserver.'],
      [2, 'Faire revenir ail, gingembre et curry, ajouter légumes, lait de coco et sauce soja. 10 min.'],
      [2, 'Cuire le riz basmati en parallèle.'],
      [3, 'Remettre le tofu, presser le citron vert au moment de servir.'],
    ],
    tip: 'Le tofu doré à part reste croustillant — ne le fais pas bouillir dans la sauce.',
  },
  {
    id: 'falafels', n: 'Falafels maison, sauce yaourt', e: '🧆', cat: 'vege', base: 'legumineuse',
    tags: ['batch', 'budget', 'street-food'], g: 1, l: 1, nu: 0, pk: 0, t: 30, c: 0, oven: 1, kcal: 540, season: [],
    ing: [['poisChiches', 0.75], ['oignon', 40], ['ail', 5], ['cumin', 0.1], ['coriandre', 0.3], ['farine', 15], ['yaourtNature', 0.5], ['citron', 0.5], ['tortillas', 1.5], ['salade', 0.2], ['huileOlive', 15]],
    steps: [
      [1, 'Mixer pois chiches égouttés, oignon, ail, cumin, coriandre et farine en pâte grossière.'],
      [1, 'Former des boulettes aplaties, les huiler.'],
      [2, 'Cuire 20 min au four à 210 °C en retournant à mi-cuisson.'],
      [1, 'Mélanger yaourt, jus de citron et un filet d’huile pour la sauce.'],
      [3, 'Garnir les tortillas de salade, falafels et sauce.'],
    ],
    tip: 'Les falafels crus se congèlent — cuisson directe sortie du congélateur (+5 min).',
  },
  {
    id: 'shakshuka', n: 'Shakshuka & pain grillé', e: '🍳', cat: 'vege', base: 'pain',
    tags: ['rapide', 'budget', 'brunch'], g: 1, l: 0, nu: 0, pk: 0, t: 10, c: 15, oven: 0, kcal: 450, season: [],
    ing: [['oeuf', 2], ['tomatesConcassees', 0.75], ['poivron', 80], ['oignon', 60], ['ail', 5], ['cumin', 0.05], ['paprika', 0.05], ['pain', 0.4], ['huileOlive', 10]],
    steps: [
      [1, "Émincer oignon, ail et poivron."],
      [2, 'Les faire revenir 5 min, ajouter tomates et épices, mijoter 10 min.'],
      [2, 'Creuser des puits, y casser les œufs, couvrir 4 min — blancs pris, jaunes coulants.'],
      [3, 'Servir à la poêle avec le pain grillé pour saucer.'],
    ],
    tip: 'La sauce se prépare en avance ; ne cuis les œufs qu’au moment de manger.',
  },
  {
    id: 'souperamen', n: 'Ramen végétarien, œuf mollet', e: '🍜', cat: 'vege', base: 'pates',
    tags: ['réconfort', 'parfumé'], g: 1, l: 0, nu: 0, pk: 0, t: 25, c: 0, oven: 0, kcal: 520, season: [10, 11, 12, 1, 2, 3],
    ing: [['nouillesAsiat', 80], ['oeuf', 1], ['champignon', 60], ['poireau', 60], ['gingembre', 8], ['ail', 5], ['sauceSoja', 20], ['bouillon', 0.5], ['sesame', 0.1]],
    steps: [
      [1, 'Émincer poireau et champignons, hacher ail et gingembre.'],
      [2, 'Cuire les œufs 6 min 30 dans l’eau bouillante, puis les passer sous l’eau froide et écaler.'],
      [2, 'Faire un bouillon : ail, gingembre, soja, cube et 500 ml d’eau, 10 min avec les légumes.'],
      [2, 'Cuire les nouilles directement dans le bouillon 4 min.'],
      [3, 'Servir avec l’œuf coupé en deux et le sésame.'],
    ],
    tip: 'L’œuf mollet 6 min 30 précisément — mets un minuteur !',
  },
  {
    id: 'saladeLentilles', n: 'Salade tiède de lentilles & feta', e: '🥙', cat: 'vege', base: 'legumineuse',
    tags: ['léger', 'budget', 'frais'], g: 0, l: 1, nu: 0, pk: 0, t: 10, c: 25, oven: 0, kcal: 470, season: [],
    ing: [['lentillesVertes', 80], ['feta', 40], ['tomateCerise', 80], ['oignonRouge', 30], ['persil', 0.3], ['moutarde', 0.1], ['vinaigre', 10], ['huileOlive', 15]],
    steps: [
      [1, "Émincer finement l'oignon rouge, couper les tomates cerises en deux."],
      [2, 'Cuire les lentilles 25 min à l’eau frémissante non salée. Égoutter.'],
      [1, 'Vinaigrette : moutarde, vinaigre, huile.'],
      [3, 'Mélanger lentilles tièdes, légumes, vinaigrette. Émietter la feta et le persil dessus.'],
    ],
    tip: 'Aussi bonne tiède que froide le lendemain au bureau.',
  },
  {
    id: 'omeletteChampi', n: 'Omelette aux champignons & salade', e: '🥚', cat: 'vege', base: 'autre',
    tags: ['rapide', 'budget', 'léger'], g: 0, l: 1, nu: 0, pk: 0, t: 15, c: 0, oven: 0, kcal: 420, season: [],
    ing: [['oeuf', 3], ['champignon', 80], ['gruyere', 20], ['salade', 0.3], ['persil', 0.2], ['beurre', 10], ['moutarde', 0.1], ['vinaigre', 5], ['huileOlive', 10]],
    steps: [
      [1, 'Émincer les champignons, battre les œufs avec le persil.'],
      [2, 'Dorer les champignons dans le beurre à feu vif 5 min.'],
      [2, 'Verser les œufs, parsemer de gruyère, cuire 3 min — le centre doit rester baveux.'],
      [3, 'Servir avec la salade en vinaigrette moutardée.'],
    ],
    tip: 'Une omelette se plie en deux et se sert immédiatement — elle n’attend personne.',
  },
  {
    id: 'padThai', n: 'Pad thaï végétarien aux cacahuètes', e: '🥜', cat: 'vege', base: 'pates',
    tags: ['parfumé', 'street-food'], g: 0, l: 0, nu: 1, pk: 0, t: 25, c: 0, oven: 0, kcal: 590, season: [],
    ing: [['nouillesAsiat', 80], ['tofuFume', 80], ['oeuf', 1], ['carotte', 60], ['beurreCacahuete', 0.2], ['sauceSoja', 20], ['citronVert', 0.5], ['ail', 5], ['coriandre', 0.2], ['huileOlive', 10]],
    steps: [
      [1, 'Tremper les nouilles selon le paquet. Tailler carotte en julienne, tofu en cubes.'],
      [1, 'Sauce : beurre de cacahuète, soja, jus de citron vert, 3 c. à s. d’eau.'],
      [2, 'Sauter tofu et carotte à feu vif, pousser sur le côté et brouiller l’œuf.'],
      [2, 'Ajouter nouilles et sauce, sauter 2 min.'],
      [3, 'Servir avec coriandre et un quartier de citron vert.'],
    ],
    tip: 'Tout doit être prêt avant d’allumer le feu — le wok ne pardonne pas les pauses.',
  },
  {
    id: 'pizzaMaison', n: 'Pizza maison aux légumes', e: '🍕', cat: 'vege', base: 'pain',
    tags: ['famille', 'fun'], g: 1, l: 1, nu: 0, pk: 0, t: 15, c: 15, oven: 1, kcal: 680, season: [],
    ing: [['pateAPizza', 0.5], ['tomatesConcassees', 0.3], ['mozzarella', 0.5], ['poivron', 50], ['champignon', 50], ['olives', 0.2], ['herbesProvence', 0.05], ['huileOlive', 5]],
    steps: [
      [1, 'Préchauffer le four à 240 °C avec la plaque dedans.'],
      [1, 'Étaler la pâte, napper de tomates, garnir de légumes émincés, mozzarella et olives.'],
      [2, 'Enfourner 12 à 15 min sur la plaque brûlante.'],
      [3, 'Huile d’olive et herbes en sortie de four.'],
    ],
    tip: 'La plaque préchauffée = pâte croustillante comme au feu de bois (ou presque).',
  },
  {
    id: 'curryChouFleur', n: 'Curry de chou-fleur rôti', e: '🥦', cat: 'vegan', base: 'riz',
    tags: ['batch', 'parfumé', 'léger'], g: 0, l: 0, nu: 0, pk: 0, t: 15, c: 30, oven: 1, kcal: 500, season: [9, 10, 11, 12, 1, 2, 3],
    ing: [['chouFleur', 200], ['poisChiches', 0.5], ['laitCoco', 0.5], ['tomatesConcassees', 0.3], ['oignon', 60], ['curryPoudre', 0.1], ['rizBasmati', 70], ['coriandre', 0.2], ['huileOlive', 10]],
    steps: [
      [1, 'Détailler le chou-fleur en fleurettes, les huiler et épicer.'],
      [2, 'Rôtir le chou-fleur 25 min à 210 °C.'],
      [2, "Pendant ce temps : revenir l'oignon, ajouter tomates, lait de coco et pois chiches, mijoter 10 min."],
      [2, 'Cuire le riz.'],
      [3, 'Mélanger le chou-fleur rôti à la sauce, servir sur le riz avec la coriandre.'],
    ],
    tip: 'Le rôtissage transforme le chou-fleur — ne saute pas cette étape.',
  },
  {
    id: 'polentaChampi', n: 'Polenta crémeuse, champignons rôtis', e: '🌽', cat: 'vege', base: 'cereale',
    tags: ['réconfort', 'budget'], g: 0, l: 1, nu: 0, pk: 0, t: 20, c: 0, oven: 0, kcal: 510, season: [9, 10, 11, 12, 1, 2],
    ing: [['polenta', 70], ['champignon', 150], ['parmesan', 20], ['beurre', 15], ['lait', 100], ['ail', 5], ['persil', 0.2], ['huileOlive', 10]],
    steps: [
      [1, "Couper les champignons en quartiers, hacher l'ail."],
      [2, 'Dorer les champignons à feu vif avec l’ail, sans les remuer trop souvent.'],
      [2, 'Verser la polenta en pluie dans lait + eau bouillants (4 volumes), remuer 8 min.'],
      [3, 'Incorporer beurre et parmesan. Servir les champignons dessus avec le persil.'],
    ],
    tip: 'La polenta fige en refroidissant : coupe les restes en frites à dorer à la poêle.',
  },
  {
    id: 'rosti', n: 'Röstis maison, œuf au plat & salade', e: '🇨🇭', cat: 'vege', base: 'pdt',
    tags: ['budget', 'terroir', 'famille'], g: 0, l: 1, nu: 0, pk: 0, t: 30, c: 0, oven: 0, kcal: 560, season: [],
    ing: [['pommeDeTerre', 250], ['oeuf', 1], ['beurre', 15], ['salade', 0.3], ['moutarde', 0.1], ['vinaigre', 5], ['huileOlive', 10]],
    steps: [
      [1, 'Râper les pommes de terre crues, bien les presser pour enlever l’eau.'],
      [2, 'Former une galette dans le beurre chaud, cuire 10 min par face à feu moyen sans y toucher.'],
      [2, 'Cuire les œufs au plat.'],
      [3, 'Servir le rösti doré avec l’œuf dessus et la salade vinaigrée.'],
    ],
    tip: 'Le secret : ne jamais remuer la galette. On la retourne d’un coup avec une assiette.',
  },
  {
    id: 'soupeBrocoli', n: 'Velouté brocoli-gruyère', e: '🥣', cat: 'vege', base: 'autre',
    tags: ['léger', 'rapide', 'réconfort'], g: 1, l: 1, nu: 0, pk: 0, t: 10, c: 20, oven: 0, kcal: 380, season: [10, 11, 12, 1, 2, 3],
    ing: [['brocoli', 200], ['pommeDeTerre', 100], ['oignon', 50], ['gruyere', 25], ['bouillon', 0.5], ['creme', 20], ['pain', 0.3]],
    steps: [
      [1, 'Couper brocoli, pomme de terre et oignon.'],
      [2, 'Cuire le tout 18 min dans le bouillon (600 ml d’eau).'],
      [3, 'Mixer, ajouter crème et gruyère, servir avec le pain grillé.'],
    ],
    tip: 'La pomme de terre donne le velouté sans crème en excès.',
  },

  /* ——— VIANDE ——— */
  {
    id: 'pouletRoti', n: 'Poulet rôti, pommes de terre fondantes', e: '🍗', cat: 'viande', base: 'pdt',
    tags: ['famille', 'dimanche', 'batch'], g: 0, l: 0, nu: 0, pk: 0, t: 15, c: 75, oven: 1, kcal: 650, season: [],
    ing: [['pouletEntier', 0.25], ['pommeDeTerre', 250], ['ail', 10], ['citron', 0.3], ['herbesProvence', 0.1], ['huileOlive', 10]],
    steps: [
      [1, 'Préchauffer le four à 200 °C. Couper les pommes de terre en quartiers.'],
      [1, 'Masser le poulet avec huile, herbes, citron et ail. Glisser un demi-citron dedans.'],
      [2, 'Enfourner 1 h 15, pommes de terre autour, en arrosant 2 fois du jus.'],
      [3, 'Laisser reposer 10 min sous une feuille d’alu avant de découper.'],
    ],
    tip: 'La carcasse fait un excellent bouillon maison — rien ne se perd.',
  },
  {
    id: 'pouletCurryCoco', n: 'Émincé de poulet curry-coco', e: '🍛', cat: 'viande', base: 'riz',
    tags: ['rapide', 'parfumé', 'batch'], g: 0, l: 0, nu: 0, pk: 0, t: 20, c: 10, oven: 0, kcal: 620, season: [],
    ing: [['pouletFilet', 130], ['laitCoco', 0.5], ['oignon', 60], ['curryPoudre', 0.1], ['gingembre', 8], ['rizBasmati', 70], ['coriandre', 0.2], ['huileOlive', 10]],
    steps: [
      [1, "Émincer le poulet et l'oignon, hacher le gingembre."],
      [2, 'Dorer le poulet à feu vif, réserver.'],
      [2, "Faire revenir oignon, gingembre et curry, remettre le poulet, ajouter le lait de coco, mijoter 10 min."],
      [2, 'Cuire le riz basmati.'],
      [3, 'Servir avec la coriandre.'],
    ],
    tip: 'Se congèle très bien en portions avec le riz — le lunch parfait.',
  },
  {
    id: 'bolognaise', n: 'Spaghetti bolognaise maison', e: '🍝', cat: 'viande', base: 'pates',
    tags: ['batch', 'famille', 'classique'], g: 1, l: 0, nu: 0, pk: 0, t: 20, c: 45, oven: 0, kcal: 680, season: [],
    ing: [['boeufHache', 120], ['pates', 100], ['tomatesConcassees', 0.75], ['carotte', 50], ['oignon', 60], ['ail', 5], ['concentreTomate', 0.3], ['herbesProvence', 0.05], ['huileOlive', 10]],
    steps: [
      [1, 'Hacher finement oignon, carotte et ail.'],
      [2, 'Faire revenir la viande à feu vif jusqu’à coloration, réserver.'],
      [2, 'Suer les légumes 5 min, remettre la viande, ajouter tomates et concentré.'],
      [2, 'Mijoter 45 min à feu doux — c’est là que tout se joue.'],
      [3, 'Cuire les spaghetti al dente et mélanger à la sauce.'],
    ],
    tip: 'Double les quantités de sauce : elle se congèle et sert pour lasagnes ou gratins.',
  },
  {
    id: 'boulettes', n: 'Boulettes sauce tomate, purée maison', e: '🧆', cat: 'viande', base: 'pdt',
    tags: ['batch', 'famille', 'réconfort'], g: 1, l: 1, nu: 0, pk: 0, t: 30, c: 20, oven: 0, kcal: 660, season: [],
    ing: [['boeufHache', 120], ['oeuf', 0.5], ['pain', 0.1], ['oignon', 50], ['tomatesConcassees', 0.5], ['pommeDeTerre', 250], ['beurre', 15], ['lait', 50], ['persil', 0.2], ['huileOlive', 10]],
    steps: [
      [1, 'Mélanger viande, œuf, mie de pain trempée, oignon haché et persil. Former des boulettes.'],
      [2, 'Cuire les pommes de terre 20 min à l’eau bouillante salée.'],
      [2, 'Dorer les boulettes, ajouter les tomates, mijoter 15 min.'],
      [3, 'Écraser les pommes de terre avec beurre et lait chaud.'],
    ],
    tip: 'Les boulettes crues se congèlent à plat — cuisson possible sans décongélation.',
  },
  {
    id: 'chiliConCarne', n: 'Chili con carne', e: '🤠', cat: 'viande', base: 'riz',
    tags: ['batch', 'épicé', 'budget'], g: 0, l: 0, nu: 0, pk: 0, t: 20, c: 40, oven: 0, kcal: 640, season: [],
    ing: [['boeufHache', 100], ['haricotsRouges', 0.5], ['tomatesConcassees', 0.5], ['oignon', 60], ['ail', 5], ['poivron', 60], ['cumin', 0.1], ['paprika', 0.1], ['riz', 70], ['huileOlive', 10]],
    steps: [
      [1, "Émincer oignon, ail et poivron."],
      [2, 'Saisir la viande à feu vif, ajouter les légumes puis tomates, haricots et épices.'],
      [2, 'Mijoter 40 min à feu doux.'],
      [2, 'Cuire le riz.'],
      [3, 'Servir avec un yaourt nature si tu veux adoucir.'],
    ],
    tip: 'Comme tous les mijotés, il est meilleur le lendemain. Congélation 3 mois.',
  },
  {
    id: 'fajitas', n: 'Fajitas de poulet', e: '🌮', cat: 'viande', base: 'pain',
    tags: ['famille', 'fun', 'rapide'], g: 1, l: 1, nu: 0, pk: 0, t: 25, c: 0, oven: 0, kcal: 630, season: [],
    ing: [['pouletFilet', 120], ['tortillas', 2], ['poivron', 80], ['oignon', 60], ['paprika', 0.1], ['cumin', 0.05], ['fromageRape', 20], ['yaourtNature', 0.5], ['citronVert', 0.3], ['huileOlive', 10]],
    steps: [
      [1, 'Émincer poulet, poivrons et oignon. Enrober le poulet d’épices.'],
      [2, 'Sauter le poulet à feu vif 5 min, puis les légumes 5 min.'],
      [3, 'Réchauffer les tortillas 30 s à la poêle.'],
      [3, 'Chacun garnit : poulet, légumes, fromage, sauce yaourt-citron vert.'],
    ],
    tip: 'Poser tout au centre de la table — le repas participatif préféré des enfants.',
  },
  {
    id: 'bourguignon', n: 'Bœuf bourguignon', e: '🍷', cat: 'viande', base: 'pdt',
    tags: ['batch', 'dimanche', 'mijoté'], g: 1, l: 0, nu: 0, pk: 0, t: 30, c: 150, oven: 0, kcal: 680, season: [10, 11, 12, 1, 2, 3],
    ing: [['boeufMijote', 180], ['carotte', 100], ['oignon', 80], ['champignon', 60], ['vinCuisine', 0.25], ['concentreTomate', 0.2], ['farine', 10], ['bouillon', 0.5], ['pommeDeTerre', 200], ['huileOlive', 15]],
    steps: [
      [1, 'Couper le bœuf en cubes, les carottes en tronçons, émincer les oignons.'],
      [2, 'Saisir la viande sur toutes les faces, singer avec la farine.'],
      [2, 'Ajouter légumes, vin, concentré et bouillon. Mijoter 2 h 30 à feu très doux.'],
      [2, 'Ajouter les champignons 30 min avant la fin. Cuire les pommes de terre vapeur.'],
      [3, 'La sauce doit napper la cuillère. Sinon, réduire à découvert 10 min.'],
    ],
    tip: 'LE plat à faire en double : il se bonifie 3 jours au frigo et se congèle 3 mois.',
  },
  {
    id: 'boeufSoja', n: 'Bœuf sauté soja-sésame, nouilles', e: '🥢', cat: 'viande', base: 'pates',
    tags: ['rapide', 'parfumé'], g: 1, l: 0, nu: 0, pk: 0, t: 20, c: 0, oven: 0, kcal: 600, season: [],
    ing: [['boeufHache', 110], ['nouillesAsiat', 80], ['brocoli', 100], ['carotte', 60], ['sauceSoja', 20], ['miel', 0.1], ['ail', 5], ['gingembre', 8], ['sesame', 0.1], ['huileOlive', 10]],
    steps: [
      [1, 'Tailler brocoli et carotte, hacher ail et gingembre. Cuire les nouilles.'],
      [2, 'Sauter la viande à feu très vif, ajouter les légumes 4 min.'],
      [2, 'Déglacer avec soja + miel + 3 c. à s. d’eau, ajouter les nouilles, 2 min.'],
      [3, 'Parsemer de sésame.'],
    ],
    tip: 'Feu au maximum et poêle bien chaude : c’est ça, le goût « wok ».',
  },
  {
    id: 'carbonara', n: 'Pâtes à la carbonara', e: '🥓', cat: 'viande', base: 'pates',
    tags: ['rapide', 'classique'], g: 1, l: 1, nu: 0, pk: 1, t: 20, c: 0, oven: 0, kcal: 720, season: [],
    ing: [['pates', 100], ['lardons', 70], ['oeuf', 1.5], ['parmesan', 30]],
    steps: [
      [1, 'Battre œufs (1 entier + 1 jaune pour 2) et parmesan. Poivrer généreusement.'],
      [2, 'Dorer les lardons à sec. Cuire les pâtes al dente.'],
      [3, 'Hors du feu : pâtes égouttées + lardons + mélange œufs-parmesan + une louche d’eau de cuisson.'],
      [3, 'Remuer vite : la sauce doit être crémeuse, jamais brouillée.'],
    ],
    tip: 'La vraie carbonara n’a pas de crème — l’œuf et l’eau de cuisson font tout.',
  },
  {
    id: 'filetMignonMoutarde', n: 'Filet mignon à la moutarde', e: '🍖', cat: 'viande', base: 'pdt',
    tags: ['dimanche', 'famille'], g: 0, l: 1, nu: 0, pk: 1, t: 15, c: 35, oven: 1, kcal: 620, season: [],
    ing: [['filetMignon', 150], ['moutarde', 0.3], ['creme', 40], ['pommeDeTerre', 220], ['echalote', 30], ['herbesProvence', 0.05], ['huileOlive', 10]],
    steps: [
      [1, 'Préchauffer le four à 190 °C. Tartiner le filet de moutarde.'],
      [2, 'Saisir le filet sur toutes les faces, enfourner 25 min avec les échalotes.'],
      [2, 'Cuire les pommes de terre vapeur en parallèle.'],
      [3, 'Déglacer le plat avec la crème pour la sauce. Trancher et napper.'],
    ],
    tip: 'Sortir la viande 15 min avant cuisson : elle sera plus tendre.',
  },
  {
    id: 'basquaise', n: 'Poulet basquaise & riz', e: '🫑', cat: 'viande', base: 'riz',
    tags: ['batch', 'mijoté', 'sud-ouest'], g: 0, l: 0, nu: 0, pk: 0, t: 20, c: 35, oven: 0, kcal: 590, season: [6, 7, 8, 9],
    ing: [['pouletCuisse', 220], ['poivron', 120], ['tomate', 150], ['oignon', 60], ['ail', 5], ['riz', 70], ['herbesProvence', 0.05], ['huileOlive', 10]],
    steps: [
      [1, 'Émincer poivrons et oignon, concasser les tomates.'],
      [2, 'Dorer les cuisses de poulet sur toutes les faces, réserver.'],
      [2, 'Faire fondre les légumes 5 min, remettre le poulet, mijoter à couvert 35 min.'],
      [2, 'Cuire le riz.'],
      [3, 'Servir le poulet nappé de sa piperade sur le riz.'],
    ],
    tip: 'Les cuisses restent moelleuses au réchauffage — parfait pour le batch.',
  },
  {
    id: 'hachisParmentier', n: 'Hachis parmentier gratiné', e: '🥧', cat: 'viande', base: 'pdt',
    tags: ['batch', 'famille', 'réconfort'], g: 0, l: 1, nu: 0, pk: 0, t: 30, c: 25, oven: 1, kcal: 640, season: [10, 11, 12, 1, 2, 3],
    ing: [['boeufHache', 120], ['pommeDeTerre', 300], ['oignon', 60], ['carotte', 50], ['lait', 60], ['beurre', 15], ['fromageRape', 25], ['concentreTomate', 0.2], ['huileOlive', 10]],
    steps: [
      [1, 'Cuire les pommes de terre 20 min, en faire une purée avec lait et beurre.'],
      [2, "Faire revenir viande, oignon et carotte hachés avec le concentré, 10 min."],
      [2, 'Monter dans un plat : viande dessous, purée dessus, râpé par-dessus.'],
      [2, 'Gratiner 25 min à 200 °C.'],
      [3, 'Servir avec une salade verte si tu en as.'],
    ],
    tip: 'Se monte la veille et s’enfourne au retour du travail. Congèle très bien.',
  },
  {
    id: 'saucisseLentilles', n: 'Saucisse fumée aux lentilles', e: '🥘', cat: 'viande', base: 'legumineuse',
    tags: ['batch', 'terroir', 'budget'], g: 0, l: 0, nu: 0, pk: 1, t: 15, c: 35, oven: 0, kcal: 630, season: [10, 11, 12, 1, 2, 3],
    ing: [['saucisseFumee', 120], ['lentillesVertes', 90], ['carotte', 80], ['oignon', 60], ['bouillon', 0.5], ['moutarde', 0.2], ['huileOlive', 10]],
    steps: [
      [1, 'Émincer oignon et carottes.'],
      [2, 'Les faire revenir, ajouter lentilles, bouillon et 3 volumes d’eau.'],
      [2, 'Poser les saucisses dessus, mijoter 35 min à couvert.'],
      [3, 'Servir avec une pointe de moutarde.'],
    ],
    tip: 'Un plat complet dans une seule cocotte — et encore meilleur réchauffé.',
  },
  {
    id: 'burgerMaison', n: 'Burger maison & potatoes', e: '🍔', cat: 'viande', base: 'pain',
    tags: ['fun', 'famille', 'week-end'], g: 1, l: 1, nu: 0, pk: 0, t: 30, c: 30, oven: 1, kcal: 780, season: [],
    ing: [['boeufHache', 130], ['painBurger', 1], ['fromageRape', 20], ['tomate', 60], ['salade', 0.2], ['oignonRouge', 30], ['pommeDeTerre', 200], ['paprika', 0.05], ['moutarde', 0.1], ['huileOlive', 15]],
    steps: [
      [1, 'Couper les pommes de terre en quartiers, huiler et saupoudrer de paprika.'],
      [2, 'Rôtir les potatoes 30 min à 210 °C.'],
      [1, 'Former les steaks, émincer tomate et oignon rouge.'],
      [2, 'Griller les steaks 3 min par face, faire fondre le fromage dessus, toaster les pains.'],
      [3, 'Monter : sauce moutarde, salade, steak, tomate, oignon.'],
    ],
    tip: 'Ne presse jamais le steak à la cuisson — c’est le jus qui fait le burger.',
  },
  {
    id: 'couscousPoulet', n: 'Couscous de poulet aux légumes', e: '🍲', cat: 'viande', base: 'cereale',
    tags: ['batch', 'famille', 'parfumé'], g: 1, l: 0, nu: 0, pk: 0, t: 25, c: 40, oven: 0, kcal: 620, season: [],
    ing: [['pouletCuisse', 200], ['carotte', 100], ['courgette', 100], ['poisChiches', 0.5], ['oignon', 60], ['tomatesConcassees', 0.5], ['cumin', 0.1], ['semoule', 80], ['huileOlive', 10]],
    steps: [
      [1, 'Couper les légumes en gros tronçons.'],
      [2, 'Dorer le poulet, ajouter oignon et cumin, puis tomates, légumes et 500 ml d’eau.'],
      [2, 'Mijoter 40 min, ajouter les pois chiches à mi-cuisson.'],
      [3, 'Préparer la semoule au dernier moment, servir le bouillon à part.'],
    ],
    tip: 'Le bouillon se ressert le lendemain avec de la semoule fraîche — deux repas en un.',
  },
  {
    id: 'pouletCitronMiel', n: 'Poulet citron-miel, riz & brocoli', e: '🍯', cat: 'viande', base: 'riz',
    tags: ['rapide', 'équilibré'], g: 0, l: 0, nu: 0, pk: 0, t: 20, c: 0, oven: 0, kcal: 580, season: [],
    ing: [['pouletFilet', 130], ['citron', 0.5], ['miel', 0.2], ['riz', 70], ['brocoli', 120], ['ail', 5], ['sauceSoja', 10], ['huileOlive', 10]],
    steps: [
      [1, 'Émincer le poulet, détailler le brocoli.'],
      [2, 'Cuire riz et brocoli vapeur (le brocoli 5 min seulement — il doit rester vert).'],
      [2, 'Dorer le poulet, déglacer avec miel, jus de citron, soja et ail. Laisser caraméliser 2 min.'],
      [3, 'Napper le riz et le brocoli de poulet laqué.'],
    ],
    tip: 'La sauce caramélise vite : reste devant la poêle sur la fin.',
  },
  {
    id: 'tartiflette', n: 'Tartiflette & salade verte', e: '🏔️', cat: 'viande', base: 'pdt',
    tags: ['réconfort', 'montagne', 'week-end'], g: 0, l: 1, nu: 0, pk: 1, t: 25, c: 30, oven: 1, kcal: 820, season: [11, 12, 1, 2, 3],
    ing: [['pommeDeTerre', 300], ['fromTartiflette', 0.5], ['lardons', 70], ['oignon', 80], ['creme', 30], ['salade', 0.3], ['moutarde', 0.1], ['vinaigre', 5], ['huileOlive', 10]],
    steps: [
      [1, 'Cuire les pommes de terre 15 min à l’eau, les trancher épais.'],
      [2, 'Dorer lardons et oignons émincés.'],
      [2, 'Monter dans un plat : pommes de terre, lardons-oignons, crème, fromage coupé en deux dans l’épaisseur, croûte vers le haut.'],
      [2, 'Enfourner 30 min à 200 °C.'],
      [3, 'Servir bien coulant avec la salade vinaigrée — l’acidité équilibre tout.'],
    ],
    tip: 'Plat des soirs d’hiver après le ski (ou pas). La salade n’est pas optionnelle. 😉',
  },

  /* ——— POISSON ——— */
  {
    id: 'saumonRoti', n: 'Saumon rôti, riz & brocoli', e: '🐟', cat: 'poisson', base: 'riz',
    tags: ['rapide', 'équilibré', 'oméga-3'], g: 0, l: 0, nu: 0, pk: 0, t: 10, c: 15, oven: 1, kcal: 610, season: [],
    ing: [['saumon', 130], ['riz', 70], ['brocoli', 120], ['citron', 0.5], ['huileOlive', 10]],
    steps: [
      [1, 'Préchauffer le four à 200 °C. Détacher les fleurettes de brocoli.'],
      [2, 'Enfourner le saumon 12 à 15 min avec citron et huile d’olive.'],
      [2, 'Cuire le riz, ajouter le brocoli vapeur les 5 dernières minutes.'],
      [3, 'Servir avec un quartier de citron.'],
    ],
    tip: 'Le saumon est cuit quand il se détache en pétales — pas une minute de plus.',
  },
  {
    id: 'poissonProvencal', n: 'Cabillaud à la provençale', e: '🍅', cat: 'poisson', base: 'riz',
    tags: ['léger', 'parfumé'], g: 0, l: 0, nu: 0, pk: 0, t: 15, c: 20, oven: 1, kcal: 480, season: [5, 6, 7, 8, 9],
    ing: [['cabillaud', 140], ['tomate', 150], ['olives', 0.3], ['oignon', 50], ['ail', 5], ['herbesProvence', 0.1], ['riz', 70], ['huileOlive', 10]],
    steps: [
      [1, 'Émincer oignon et ail, couper les tomates.'],
      [2, 'Compoter tomates, oignon, ail, olives et herbes 10 min.'],
      [2, 'Poser le cabillaud sur la compotée dans un plat, enfourner 15 min à 190 °C.'],
      [2, 'Cuire le riz.'],
      [3, 'Arroser le poisson du jus de cuisson au moment de servir.'],
    ],
    tip: 'Marche avec n’importe quel poisson blanc — prends celui en promo.',
  },
  {
    id: 'patesThon', n: 'Pâtes au thon, citron & olives', e: '🍋', cat: 'poisson', base: 'pates',
    tags: ['rapide', 'budget', 'placard'], g: 1, l: 0, nu: 0, pk: 0, t: 15, c: 0, oven: 0, kcal: 570, season: [],
    ing: [['pates', 100], ['thon', 0.75], ['olives', 0.3], ['citron', 0.5], ['ail', 5], ['persil', 0.2], ['huileOlive', 15]],
    steps: [
      [1, 'Hacher ail et persil, zester le citron.'],
      [2, 'Cuire les pâtes al dente.'],
      [3, 'Mélanger pâtes, thon égoutté, olives, ail, zeste + jus de citron et huile d’olive.'],
      [3, 'Terminer par le persil, poivrer généreusement.'],
    ],
    tip: 'Le dîner de secours par excellence : 15 minutes, que du placard.',
  },
  {
    id: 'crevettesAil', n: 'Crevettes sautées ail & citron, riz', e: '🍤', cat: 'poisson', base: 'riz',
    tags: ['rapide', 'léger', 'festif'], g: 0, l: 0, nu: 0, pk: 0, t: 15, c: 0, oven: 0, kcal: 480, season: [],
    ing: [['crevettes', 130], ['riz', 70], ['ail', 8], ['citron', 0.5], ['persil', 0.3], ['petitsPois', 80], ['huileOlive', 15]],
    steps: [
      [1, "Hacher l'ail et le persil."],
      [2, 'Cuire le riz, ajouter les petits pois les 3 dernières minutes.'],
      [2, "Sauter les crevettes 2 min par face à feu vif avec l'ail."],
      [3, 'Déglacer au jus de citron, ajouter le persil, servir sur le riz.'],
    ],
    tip: 'Les crevettes cuisent en 4 minutes chrono — au-delà, elles deviennent caoutchouc.',
  },
  {
    id: 'pokeBowl', n: 'Poke bowl saumon-avocat', e: '🥢', cat: 'poisson', base: 'riz',
    tags: ['frais', 'été', 'sans cuisson'], g: 0, l: 0, nu: 0, pk: 0, t: 25, c: 0, oven: 0, kcal: 620, season: [5, 6, 7, 8, 9],
    ing: [['saumon', 120], ['rizBasmati', 75], ['avocat', 0.5], ['concombre', 0.3], ['carotte', 50], ['sauceSoja', 15], ['sesame', 0.2], ['citronVert', 0.5], ['gingembre', 5]],
    steps: [
      [1, 'Cuire le riz, le laisser tiédir avec un trait de vinaigre si tu en as.'],
      [1, 'Couper le saumon très frais en cubes, le mariner 10 min : soja, citron vert, gingembre.'],
      [1, 'Tailler avocat, concombre et carotte.'],
      [3, 'Dresser en bol sur le riz tiède, parsemer de sésame.'],
    ],
    tip: 'Saumon « qualité sushi » ou préalablement congelé 48 h — fraîcheur irréprochable exigée.',
  },
  {
    id: 'gratinPoisson', n: 'Gratin de poisson aux poireaux', e: '🐠', cat: 'poisson', base: 'pdt',
    tags: ['famille', 'réconfort', 'batch'], g: 0, l: 1, nu: 0, pk: 0, t: 25, c: 25, oven: 1, kcal: 560, season: [10, 11, 12, 1, 2, 3],
    ing: [['cabillaud', 130], ['poireau', 150], ['pommeDeTerre', 250], ['creme', 50], ['fromageRape', 25], ['beurre', 10]],
    steps: [
      [1, 'Émincer les poireaux, trancher finement les pommes de terre.'],
      [2, 'Faire fondre les poireaux au beurre 10 min. Précuire les pommes de terre 10 min à l’eau.'],
      [2, 'Monter dans un plat : pommes de terre, poireaux, poisson en morceaux, crème, râpé.'],
      [2, 'Gratiner 25 min à 190 °C.'],
      [3, 'Laisser reposer 5 min avant de servir.'],
    ],
    tip: 'Poireau + poisson + crème : le trio gagnant des soirs d’hiver.',
  },
];

/* Moyennes utilisées pour l'estimation des économies (repas livré / plat préparé) */
const PRIX_REPAS_REF = { FR: 12, CH: 19 };
